### ISSUE TITLE
If trying to get for a station multiple times crashes

### ISSUE THREAD

**Issue by cflexible** [FL550/simple_dwd_weatherforecast#12] opened 2023-08-23 06:50 UTC
If I call this
temperature    = dwd_weather.get_forecast_data(dwdforecast.WeatherDataType.TEMPERATURE, time)
multiple times for the same dwd_weather (the same station) it crashes (want to use different times):
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 239, in get_forecast_data
    if self.is_in_timerange(timestamp):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 219, in is_in_timerange
    list(self.forecast_data.keys())[0]
         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by FL550** [comment] 2023-08-25 06:23
Thanks for reaching out. Can you please provide me the full station name from which you are trying to retrieve the data?

**Comment by cflexible** [comment] 2023-08-25 08:19
Hi,
the problem is independent from the station, but you can use P829

Regards,
Jens

**Comment by FL550** [comment] 2023-08-25 08:33
Ok, so then it might be related to connection problems. This error can only occur if there were retrieved no or only erroneous data. I could improve the error handling to make this more transparent and make troubleshooting more easily.

**Comment by cflexible** [comment] 2023-08-25 08:38
I don’t think that it is an error handling problem because the error occurs every time I asked about the temperature for the same station with different dates. I think there might be a problem with an initialisation of a variable in dwdforecast.Weather(weather_station)
when using the same station.
If I change the station it works but if I use for example the first station again, it crashes.

**Comment by FL550** [comment] 2023-08-25 12:03
Oh, now I understand you. Can you please provide a code snippet which produces the error?

**Comment by cflexible** [comment] 2023-08-25 12:10
You can use this:
￼

**Comment by FL550** [comment] 2023-09-02 13:35
This hasn't worked unfortunately. The code is not visible for me. Can you please send me the snippet again?

**Comment by cflexible** [comment] 2023-09-02 16:33
￼
I have zipped the file now. Hopefully you can see it now.

**Comment by FL550** [comment] 2023-09-09 07:53
Hi, first of all, sorry for the late replies. I was not at home. Unfortunately, I can't see your code. Can you please try to attach the code via the webbrowser instead of mail?

**Comment by cflexible** [comment] 2023-09-09 08:07
Hi, here is the code:

```python
from geopy.geocoders import Nominatim

# Initialize Nominatim API
geolocator = Nominatim(user_agent="MyChatbot")

# For the weather forecast the dwd (Deutscher Wetter Dfrom simple_dwd_weatherforecast import dwdforecast
from simple_dwd_weatherforecast import dwdforecast
from datetime import datetime, timedelta, timezone

# Weather functions
# Return the location information for a given city name
def getLocation(name):
    if name is None:
        return None
    try:
        location = geolocator.geocode(name)
    except:
        global errorMessage
        errorMessage = "Error while looking for location"
        return None
    return location 



# Returns the weather (the temperature and the cloud coverage) for a location
# This is just an example. A lot of more values are possible.
def getWeather(location, time):
    if location is None:
        return None

    # Attention: There is a bug in the simple_dwd_weatherforecast library. If you call the next functions multiple times for the
    # same locationit crashes. I have sent a bug report to the developers on github.com.
    try: 
        next_weather_station = dwdforecast.get_nearest_station_id(location.latitude, location.longitude)
        if next_weather_station is not None:
            print("Station ID found: ", next_weather_station)
            dwd_weather = dwdforecast.Weather(next_weather_station)
            # print("Looking for weather at ", next_weather_station, " for time ", time)
            temperature    = dwd_weather.get_forecast_data(dwdforecast.WeatherDataType.TEMPERATURE, time) - 273.16
            cloud_coverage = dwd_weather.get_forecast_data(dwdforecast.WeatherDataType.CLOUD_COVERAGE, time)
            return temperature, cloud_coverage
        else:
            return None
    except:
        global errorMessage
        errorMessage = "Error while looking for weather"
        return None, None

myLocation = getLocation('Altenstadt')
time_now = datetime.today()
time_tomorrow = datetime.today() + timedelta(days=+1)
print(getWeather(myLocation, time_now))
print(getWeather(myLocation, time_tomorrow))
```

**Comment by FL550** [comment] 2023-09-09 09:51
Ok, I see. You are forcing a new init of the Weather class without actually requesting the new weather data. With your approach there will be a second request to the DWD server which is unnecessary, as the class stores the data for the next days in a single request. 

Here is a modified version of your code, which performs your request:
```python
from geopy.geocoders import Nominatim

# Initialize Nominatim API
geolocator = Nominatim(user_agent="MyChatbot")

# For the weather forecast the dwd (Deutscher Wetter Dfrom simple_dwd_weatherforecast import dwdforecast
from simple_dwd_weatherforecast import dwdforecast
from datetime import datetime, timedelta, timezone

# Weather functions
# Return the location information for a given city name
def getLocation(name):
    if name is None:
        return None
    try:
        location = geolocator.geocode(name)
    except:
        global errorMessage
        errorMessage = "Error while looking for location"
        return None
    return location

class CustomWeather:
    weather_station = None
    def __init__(self, location):
        next_station_id = dwdforecast.get_nearest_station_id(location.latitude, location.longitude)
        print("Station ID found: ", next_station_id)
        self.weather_station = dwdforecast.Weather(next_station_id)
    
    def getWeather(self, time):
        # print("Looking for weather at ", next_weather_station, " for time ", time)
        temperature    = round(self.weather_station.get_forecast_data(dwdforecast.WeatherDataType.TEMPERATURE, time) - 273.16, 2)
        cloud_coverage = self.weather_station.get_forecast_data(dwdforecast.WeatherDataType.CLOUD_COVERAGE, time)
        return temperature, cloud_coverage

myLocation = getLocation('Altenstadt')
# Init the CustomWeatherClass
myWeather = CustomWeather(myLocation)

time_now = datetime.today()
time_tomorrow = datetime.today() + timedelta(days=+1)

print(myWeather.getWeather(time_now))
print(myWeather.getWeather(time_tomorrow))
```

I hope this helps.

**Comment by cflexible** [comment] 2023-09-09 10:51
Hi,
the problem was something else. I did not say that the actual weather station variable is global. Now it is solved.

Thanks for your assistance.

Regards,
Jens

**Comment by FL550** [comment] 2023-09-09 11:10
Ok. Glad you could resolve it. May I close this issue then?

**Comment by cflexible** [comment] 2023-09-09 13:00
Yes, but you should have a look to the exception. Perhaps you could handle that also internally.

**Comment by FL550** [comment] 2023-09-09 13:49
I agree. But can you please give me then a code example which produces this error? I was unable to reproduce this.

**Comment by cflexible** [comment] 2023-09-09 15:15
On what kind of system do you run my script? I have a M1 Mac with Python 3.11.4
Perhaps there is a problem in the main system.
I have updated my code to get a reason.


```python
        if next_weather_station is not None:
            print("Station ID found: ", next_weather_station)
            global dwd_weather
            dwd_weather = dwdforecast.Weather(next_weather_station)
            print(dwd_weather)
            # print("Looking for weather at ", next_weather_station, " for time ", time)
            temperature    = dwd_weather.get_forecast_data(dwdforecast.WeatherDataType.TEMPERATURE, time) - 273.16
            cloud_coverage = dwd_weather.get_forecast_data(dwdforecast.WeatherDataType.CLOUD_COVERAGE, time)
            return temperature, cloud_coverage
        else:
             return None
    except Exception as e:
        global errorMessage
        errorMessage = "Error while looking for weather: " + str(e)
        print(errorMessage)
        return None, None


Here the output:
Station ID found:  P829
<simple_dwd_weatherforecast.dwdforecast.Weather object at 0x102de3750>
(24.989999999999952, 19.0)
Station ID found:  P829
<simple_dwd_weatherforecast.dwdforecast.Weather object at 0x102dee850>
Error while looking for weather: 'NoneType' object has no attribute 'keys'
(None, None)
```

As you can see, I have two different dwd_weather objects (with the same location) and the second object throws the error. I think, you have some global variables in the class which are not full reloaded because you check if you already have read them.

**Comment by FL550** [comment] 2023-09-18 10:21
You have found indeed a little bug, which will be fixed if I release the new version in a few days. However, I would like to advise not calling the same station_id from different Weather objects. The problem is, that there will be seperate calls to the DWD server which is avoided otherwise. Best regards

**Closed as completed** 2023-10-05 08:51 UTC
